// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.21.12
// source: sync.proto

package micro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 同步消息
type Sync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Full    bool     `protobuf:"varint,1,opt,name=full,proto3" json:"full,omitempty"`            // 是否全量同步
	Serial  string   `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`         // 电柜编码
	Cabinet *Cabinet `protobuf:"bytes,3,opt,name=cabinet,proto3,oneof" json:"cabinet,omitempty"` // 电柜
	Bins    []*Bin   `protobuf:"bytes,4,rep,name=bins,proto3" json:"bins,omitempty"`             // 仓位
}

func (x *Sync) Reset() {
	*x = Sync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Sync) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *Sync) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Sync) GetCabinet() *Cabinet {
	if x != nil {
		return x.Cabinet
	}
	return nil
}

func (x *Sync) GetBins() []*Bin {
	if x != nil {
		return x.Bins
	}
	return nil
}

type Cabinet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Online bool     `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`  // 是否在线
	Brand  string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`     // 品牌
	Serial string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`   // 电柜编号
	Status string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`   // 状态
	Enable bool     `protobuf:"varint,6,opt,name=enable,proto3" json:"enable,omitempty"`  // 是否启用
	Lng    *float32 `protobuf:"fixed32,7,opt,name=lng,proto3,oneof" json:"lng,omitempty"` // 经度
	Lat    *float32 `protobuf:"fixed32,8,opt,name=lat,proto3,oneof" json:"lat,omitempty"` // 纬度
	Gsm    *float32 `protobuf:"fixed32,9,opt,name=gsm,proto3,oneof" json:"gsm,omitempty"` // GSM信号强度
}

func (x *Cabinet) Reset() {
	*x = Cabinet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cabinet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cabinet) ProtoMessage() {}

func (x *Cabinet) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cabinet.ProtoReflect.Descriptor instead.
func (*Cabinet) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *Cabinet) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Cabinet) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Cabinet) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Cabinet) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Cabinet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Cabinet) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Cabinet) GetLng() float32 {
	if x != nil && x.Lng != nil {
		return *x.Lng
	}
	return 0
}

func (x *Cabinet) GetLat() float32 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Cabinet) GetGsm() float32 {
	if x != nil && x.Gsm != nil {
		return *x.Gsm
	}
	return 0
}

type Bin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *Bin) Reset() {
	*x = Bin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bin) ProtoMessage() {}

func (x *Bin) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bin.ProtoReflect.Descriptor instead.
func (*Bin) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Bin) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_sync_proto protoreflect.FileDescriptor

var file_sync_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x75, 0x6c, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x61, 0x62, 0x69,
	0x6e, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x43, 0x61, 0x62, 0x69, 0x6e, 0x65, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x61, 0x62,
	0x69, 0x6e, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x69, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x42, 0x69,
	0x6e, 0x52, 0x04, 0x62, 0x69, 0x6e, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x61, 0x62, 0x69,
	0x6e, 0x65, 0x74, 0x22, 0xec, 0x01, 0x0a, 0x07, 0x43, 0x61, 0x62, 0x69, 0x6e, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74,
	0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x67, 0x73, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x02, 0x52, 0x03, 0x67, 0x73, 0x6d, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6c,
	0x6e, 0x67, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6c, 0x61, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x67,
	0x73, 0x6d, 0x22, 0x15, 0x0a, 0x03, 0x42, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x32, 0x0e, 0x0a, 0x0c, 0x53, 0x79, 0x6e,
	0x63, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x72, 0x6f, 0x72, 0x61, 0x72, 0x69,
	0x64, 0x65, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData = file_sync_proto_rawDesc
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_proto_rawDescData)
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sync_proto_goTypes = []interface{}{
	(*Sync)(nil),    // 0: micro.Sync
	(*Cabinet)(nil), // 1: micro.Cabinet
	(*Bin)(nil),     // 2: micro.Bin
}
var file_sync_proto_depIdxs = []int32{
	1, // 0: micro.Sync.cabinet:type_name -> micro.Cabinet
	2, // 1: micro.Sync.bins:type_name -> micro.Bin
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cabinet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sync_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_sync_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_rawDesc = nil
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
