// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/auroraride/adapter/defs/xcdef/ent/battery"
	"github.com/auroraride/adapter/defs/xcdef/ent/fault"
	"github.com/auroraride/adapter/defs/xcdef/ent/heartbeat"
	"github.com/auroraride/adapter/defs/xcdef/ent/predicate"
	"github.com/auroraride/adapter/defs/xcdef/ent/reign"
)

// BatteryQuery is the builder for querying Battery entities.
type BatteryQuery struct {
	config
	ctx                 *QueryContext
	order               []OrderFunc
	inters              []Interceptor
	predicates          []predicate.Battery
	withHeartbeats      *HeartbeatQuery
	withReigns          *ReignQuery
	withFaultLog        *FaultQuery
	modifiers           []func(*sql.Selector)
	withNamedHeartbeats map[string]*HeartbeatQuery
	withNamedReigns     map[string]*ReignQuery
	withNamedFaultLog   map[string]*FaultQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BatteryQuery builder.
func (bq *BatteryQuery) Where(ps ...predicate.Battery) *BatteryQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BatteryQuery) Limit(limit int) *BatteryQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BatteryQuery) Offset(offset int) *BatteryQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BatteryQuery) Unique(unique bool) *BatteryQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BatteryQuery) Order(o ...OrderFunc) *BatteryQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryHeartbeats chains the current query on the "heartbeats" edge.
func (bq *BatteryQuery) QueryHeartbeats() *HeartbeatQuery {
	query := (&HeartbeatClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(battery.Table, battery.FieldID, selector),
			sqlgraph.To(heartbeat.Table, heartbeat.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, battery.HeartbeatsTable, battery.HeartbeatsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReigns chains the current query on the "reigns" edge.
func (bq *BatteryQuery) QueryReigns() *ReignQuery {
	query := (&ReignClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(battery.Table, battery.FieldID, selector),
			sqlgraph.To(reign.Table, reign.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, battery.ReignsTable, battery.ReignsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFaultLog chains the current query on the "fault_log" edge.
func (bq *BatteryQuery) QueryFaultLog() *FaultQuery {
	query := (&FaultClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(battery.Table, battery.FieldID, selector),
			sqlgraph.To(fault.Table, fault.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, battery.FaultLogTable, battery.FaultLogColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Battery entity from the query.
// Returns a *NotFoundError when no Battery was found.
func (bq *BatteryQuery) First(ctx context.Context) (*Battery, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{battery.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BatteryQuery) FirstX(ctx context.Context) *Battery {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Battery ID from the query.
// Returns a *NotFoundError when no Battery ID was found.
func (bq *BatteryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{battery.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BatteryQuery) FirstIDX(ctx context.Context) int {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Battery entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Battery entity is found.
// Returns a *NotFoundError when no Battery entities are found.
func (bq *BatteryQuery) Only(ctx context.Context) (*Battery, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{battery.Label}
	default:
		return nil, &NotSingularError{battery.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BatteryQuery) OnlyX(ctx context.Context) *Battery {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Battery ID in the query.
// Returns a *NotSingularError when more than one Battery ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BatteryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{battery.Label}
	default:
		err = &NotSingularError{battery.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BatteryQuery) OnlyIDX(ctx context.Context) int {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Batteries.
func (bq *BatteryQuery) All(ctx context.Context) ([]*Battery, error) {
	ctx = setContextOp(ctx, bq.ctx, "All")
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Battery, *BatteryQuery]()
	return withInterceptors[[]*Battery](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BatteryQuery) AllX(ctx context.Context) []*Battery {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Battery IDs.
func (bq *BatteryQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, bq.ctx, "IDs")
	if err := bq.Select(battery.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BatteryQuery) IDsX(ctx context.Context) []int {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BatteryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, "Count")
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BatteryQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BatteryQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BatteryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, "Exist")
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BatteryQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BatteryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BatteryQuery) Clone() *BatteryQuery {
	if bq == nil {
		return nil
	}
	return &BatteryQuery{
		config:         bq.config,
		ctx:            bq.ctx.Clone(),
		order:          append([]OrderFunc{}, bq.order...),
		inters:         append([]Interceptor{}, bq.inters...),
		predicates:     append([]predicate.Battery{}, bq.predicates...),
		withHeartbeats: bq.withHeartbeats.Clone(),
		withReigns:     bq.withReigns.Clone(),
		withFaultLog:   bq.withFaultLog.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithHeartbeats tells the query-builder to eager-load the nodes that are connected to
// the "heartbeats" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BatteryQuery) WithHeartbeats(opts ...func(*HeartbeatQuery)) *BatteryQuery {
	query := (&HeartbeatClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withHeartbeats = query
	return bq
}

// WithReigns tells the query-builder to eager-load the nodes that are connected to
// the "reigns" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BatteryQuery) WithReigns(opts ...func(*ReignQuery)) *BatteryQuery {
	query := (&ReignClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withReigns = query
	return bq
}

// WithFaultLog tells the query-builder to eager-load the nodes that are connected to
// the "fault_log" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BatteryQuery) WithFaultLog(opts ...func(*FaultQuery)) *BatteryQuery {
	query := (&FaultClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withFaultLog = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Battery.Query().
//		GroupBy(battery.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BatteryQuery) GroupBy(field string, fields ...string) *BatteryGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BatteryGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = battery.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Battery.Query().
//		Select(battery.FieldCreatedAt).
//		Scan(ctx, &v)
func (bq *BatteryQuery) Select(fields ...string) *BatterySelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BatterySelect{BatteryQuery: bq}
	sbuild.label = battery.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BatterySelect configured with the given aggregations.
func (bq *BatteryQuery) Aggregate(fns ...AggregateFunc) *BatterySelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BatteryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !battery.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BatteryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Battery, error) {
	var (
		nodes       = []*Battery{}
		_spec       = bq.querySpec()
		loadedTypes = [3]bool{
			bq.withHeartbeats != nil,
			bq.withReigns != nil,
			bq.withFaultLog != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Battery).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Battery{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(bq.modifiers) > 0 {
		_spec.Modifiers = bq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withHeartbeats; query != nil {
		if err := bq.loadHeartbeats(ctx, query, nodes,
			func(n *Battery) { n.Edges.Heartbeats = []*Heartbeat{} },
			func(n *Battery, e *Heartbeat) { n.Edges.Heartbeats = append(n.Edges.Heartbeats, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withReigns; query != nil {
		if err := bq.loadReigns(ctx, query, nodes,
			func(n *Battery) { n.Edges.Reigns = []*Reign{} },
			func(n *Battery, e *Reign) { n.Edges.Reigns = append(n.Edges.Reigns, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withFaultLog; query != nil {
		if err := bq.loadFaultLog(ctx, query, nodes,
			func(n *Battery) { n.Edges.FaultLog = []*Fault{} },
			func(n *Battery, e *Fault) { n.Edges.FaultLog = append(n.Edges.FaultLog, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range bq.withNamedHeartbeats {
		if err := bq.loadHeartbeats(ctx, query, nodes,
			func(n *Battery) { n.appendNamedHeartbeats(name) },
			func(n *Battery, e *Heartbeat) { n.appendNamedHeartbeats(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range bq.withNamedReigns {
		if err := bq.loadReigns(ctx, query, nodes,
			func(n *Battery) { n.appendNamedReigns(name) },
			func(n *Battery, e *Reign) { n.appendNamedReigns(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range bq.withNamedFaultLog {
		if err := bq.loadFaultLog(ctx, query, nodes,
			func(n *Battery) { n.appendNamedFaultLog(name) },
			func(n *Battery, e *Fault) { n.appendNamedFaultLog(name, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BatteryQuery) loadHeartbeats(ctx context.Context, query *HeartbeatQuery, nodes []*Battery, init func(*Battery), assign func(*Battery, *Heartbeat)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Battery)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Heartbeat(func(s *sql.Selector) {
		s.Where(sql.InValues(battery.HeartbeatsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BatteryID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "battery_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BatteryQuery) loadReigns(ctx context.Context, query *ReignQuery, nodes []*Battery, init func(*Battery), assign func(*Battery, *Reign)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Battery)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Reign(func(s *sql.Selector) {
		s.Where(sql.InValues(battery.ReignsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BatteryID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "battery_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BatteryQuery) loadFaultLog(ctx context.Context, query *FaultQuery, nodes []*Battery, init func(*Battery), assign func(*Battery, *Fault)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Battery)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Fault(func(s *sql.Selector) {
		s.Where(sql.InValues(battery.FaultLogColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BatteryID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "battery_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bq *BatteryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	if len(bq.modifiers) > 0 {
		_spec.Modifiers = bq.modifiers
	}
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BatteryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   battery.Table,
			Columns: battery.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: battery.FieldID,
			},
		},
		From:   bq.sql,
		Unique: true,
	}
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, battery.FieldID)
		for i := range fields {
			if fields[i] != battery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BatteryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(battery.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = battery.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range bq.modifiers {
		m(selector)
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bq *BatteryQuery) Modify(modifiers ...func(s *sql.Selector)) *BatterySelect {
	bq.modifiers = append(bq.modifiers, modifiers...)
	return bq.Select()
}

// WithNamedHeartbeats tells the query-builder to eager-load the nodes that are connected to the "heartbeats"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (bq *BatteryQuery) WithNamedHeartbeats(name string, opts ...func(*HeartbeatQuery)) *BatteryQuery {
	query := (&HeartbeatClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if bq.withNamedHeartbeats == nil {
		bq.withNamedHeartbeats = make(map[string]*HeartbeatQuery)
	}
	bq.withNamedHeartbeats[name] = query
	return bq
}

// WithNamedReigns tells the query-builder to eager-load the nodes that are connected to the "reigns"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (bq *BatteryQuery) WithNamedReigns(name string, opts ...func(*ReignQuery)) *BatteryQuery {
	query := (&ReignClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if bq.withNamedReigns == nil {
		bq.withNamedReigns = make(map[string]*ReignQuery)
	}
	bq.withNamedReigns[name] = query
	return bq
}

// WithNamedFaultLog tells the query-builder to eager-load the nodes that are connected to the "fault_log"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (bq *BatteryQuery) WithNamedFaultLog(name string, opts ...func(*FaultQuery)) *BatteryQuery {
	query := (&FaultClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if bq.withNamedFaultLog == nil {
		bq.withNamedFaultLog = make(map[string]*FaultQuery)
	}
	bq.withNamedFaultLog[name] = query
	return bq
}

// BatteryGroupBy is the group-by builder for Battery entities.
type BatteryGroupBy struct {
	selector
	build *BatteryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BatteryGroupBy) Aggregate(fns ...AggregateFunc) *BatteryGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BatteryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, "GroupBy")
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BatteryQuery, *BatteryGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BatteryGroupBy) sqlScan(ctx context.Context, root *BatteryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BatterySelect is the builder for selecting fields of Battery entities.
type BatterySelect struct {
	*BatteryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BatterySelect) Aggregate(fns ...AggregateFunc) *BatterySelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BatterySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, "Select")
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BatteryQuery, *BatterySelect](ctx, bs.BatteryQuery, bs, bs.inters, v)
}

func (bs *BatterySelect) sqlScan(ctx context.Context, root *BatteryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bs *BatterySelect) Modify(modifiers ...func(s *sql.Selector)) *BatterySelect {
	bs.modifiers = append(bs.modifiers, modifiers...)
	return bs
}
