// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/auroraride/adapter/defs/xcdef/ent/battery"
	"github.com/auroraride/adapter/defs/xcdef/ent/fault"
	"github.com/auroraride/adapter/defs/xcdef/ent/predicate"
)

// FaultQuery is the builder for querying Fault entities.
type FaultQuery struct {
	config
	ctx         *QueryContext
	order       []OrderFunc
	inters      []Interceptor
	predicates  []predicate.Fault
	withBattery *BatteryQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FaultQuery builder.
func (fq *FaultQuery) Where(ps ...predicate.Fault) *FaultQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *FaultQuery) Limit(limit int) *FaultQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *FaultQuery) Offset(offset int) *FaultQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FaultQuery) Unique(unique bool) *FaultQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *FaultQuery) Order(o ...OrderFunc) *FaultQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryBattery chains the current query on the "battery" edge.
func (fq *FaultQuery) QueryBattery() *BatteryQuery {
	query := (&BatteryClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fault.Table, fault.FieldID, selector),
			sqlgraph.To(battery.Table, battery.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fault.BatteryTable, fault.BatteryColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Fault entity from the query.
// Returns a *NotFoundError when no Fault was found.
func (fq *FaultQuery) First(ctx context.Context) (*Fault, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fault.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FaultQuery) FirstX(ctx context.Context) *Fault {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Fault ID from the query.
// Returns a *NotFoundError when no Fault ID was found.
func (fq *FaultQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fault.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FaultQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Fault entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Fault entity is found.
// Returns a *NotFoundError when no Fault entities are found.
func (fq *FaultQuery) Only(ctx context.Context) (*Fault, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fault.Label}
	default:
		return nil, &NotSingularError{fault.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FaultQuery) OnlyX(ctx context.Context) *Fault {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Fault ID in the query.
// Returns a *NotSingularError when more than one Fault ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FaultQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fault.Label}
	default:
		err = &NotSingularError{fault.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FaultQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Faults.
func (fq *FaultQuery) All(ctx context.Context) ([]*Fault, error) {
	ctx = setContextOp(ctx, fq.ctx, "All")
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Fault, *FaultQuery]()
	return withInterceptors[[]*Fault](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *FaultQuery) AllX(ctx context.Context) []*Fault {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Fault IDs.
func (fq *FaultQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, fq.ctx, "IDs")
	if err := fq.Select(fault.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FaultQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FaultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, "Count")
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*FaultQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FaultQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FaultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, "Exist")
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FaultQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FaultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FaultQuery) Clone() *FaultQuery {
	if fq == nil {
		return nil
	}
	return &FaultQuery{
		config:      fq.config,
		ctx:         fq.ctx.Clone(),
		order:       append([]OrderFunc{}, fq.order...),
		inters:      append([]Interceptor{}, fq.inters...),
		predicates:  append([]predicate.Fault{}, fq.predicates...),
		withBattery: fq.withBattery.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithBattery tells the query-builder to eager-load the nodes that are connected to
// the "battery" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FaultQuery) WithBattery(opts ...func(*BatteryQuery)) *FaultQuery {
	query := (&BatteryClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withBattery = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sn string `json:"sn,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Fault.Query().
//		GroupBy(fault.FieldSn).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *FaultQuery) GroupBy(field string, fields ...string) *FaultGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FaultGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = fault.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Sn string `json:"sn,omitempty"`
//	}
//
//	client.Fault.Query().
//		Select(fault.FieldSn).
//		Scan(ctx, &v)
func (fq *FaultQuery) Select(fields ...string) *FaultSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &FaultSelect{FaultQuery: fq}
	sbuild.label = fault.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FaultSelect configured with the given aggregations.
func (fq *FaultQuery) Aggregate(fns ...AggregateFunc) *FaultSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *FaultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !fault.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FaultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Fault, error) {
	var (
		nodes       = []*Fault{}
		_spec       = fq.querySpec()
		loadedTypes = [1]bool{
			fq.withBattery != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Fault).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Fault{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(fq.modifiers) > 0 {
		_spec.Modifiers = fq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withBattery; query != nil {
		if err := fq.loadBattery(ctx, query, nodes, nil,
			func(n *Fault, e *Battery) { n.Edges.Battery = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *FaultQuery) loadBattery(ctx context.Context, query *BatteryQuery, nodes []*Fault, init func(*Fault), assign func(*Fault, *Battery)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Fault)
	for i := range nodes {
		fk := nodes[i].BatteryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(battery.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "battery_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (fq *FaultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	if len(fq.modifiers) > 0 {
		_spec.Modifiers = fq.modifiers
	}
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FaultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fault.Table,
			Columns: fault.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fault.FieldID,
			},
		},
		From:   fq.sql,
		Unique: true,
	}
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fault.FieldID)
		for i := range fields {
			if fields[i] != fault.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FaultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(fault.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = fault.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range fq.modifiers {
		m(selector)
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (fq *FaultQuery) Modify(modifiers ...func(s *sql.Selector)) *FaultSelect {
	fq.modifiers = append(fq.modifiers, modifiers...)
	return fq.Select()
}

// FaultGroupBy is the group-by builder for Fault entities.
type FaultGroupBy struct {
	selector
	build *FaultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FaultGroupBy) Aggregate(fns ...AggregateFunc) *FaultGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *FaultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, "GroupBy")
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FaultQuery, *FaultGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *FaultGroupBy) sqlScan(ctx context.Context, root *FaultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FaultSelect is the builder for selecting fields of Fault entities.
type FaultSelect struct {
	*FaultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *FaultSelect) Aggregate(fns ...AggregateFunc) *FaultSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FaultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, "Select")
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FaultQuery, *FaultSelect](ctx, fs.FaultQuery, fs, fs.inters, v)
}

func (fs *FaultSelect) sqlScan(ctx context.Context, root *FaultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (fs *FaultSelect) Modify(modifiers ...func(s *sql.Selector)) *FaultSelect {
	fs.modifiers = append(fs.modifiers, modifiers...)
	return fs
}
