// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/auroraride/adapter/defs/xcdef/ent/battery"
	"github.com/auroraride/adapter/defs/xcdef/ent/predicate"
	"github.com/auroraride/adapter/defs/xcdef/ent/reign"
)

// ReignQuery is the builder for querying Reign entities.
type ReignQuery struct {
	config
	ctx         *QueryContext
	order       []OrderFunc
	inters      []Interceptor
	predicates  []predicate.Reign
	withBattery *BatteryQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReignQuery builder.
func (rq *ReignQuery) Where(ps ...predicate.Reign) *ReignQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *ReignQuery) Limit(limit int) *ReignQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *ReignQuery) Offset(offset int) *ReignQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *ReignQuery) Unique(unique bool) *ReignQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *ReignQuery) Order(o ...OrderFunc) *ReignQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryBattery chains the current query on the "battery" edge.
func (rq *ReignQuery) QueryBattery() *BatteryQuery {
	query := (&BatteryClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reign.Table, reign.FieldID, selector),
			sqlgraph.To(battery.Table, battery.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, reign.BatteryTable, reign.BatteryColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Reign entity from the query.
// Returns a *NotFoundError when no Reign was found.
func (rq *ReignQuery) First(ctx context.Context) (*Reign, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{reign.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *ReignQuery) FirstX(ctx context.Context) *Reign {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Reign ID from the query.
// Returns a *NotFoundError when no Reign ID was found.
func (rq *ReignQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{reign.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *ReignQuery) FirstIDX(ctx context.Context) int {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Reign entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Reign entity is found.
// Returns a *NotFoundError when no Reign entities are found.
func (rq *ReignQuery) Only(ctx context.Context) (*Reign, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{reign.Label}
	default:
		return nil, &NotSingularError{reign.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *ReignQuery) OnlyX(ctx context.Context) *Reign {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Reign ID in the query.
// Returns a *NotSingularError when more than one Reign ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *ReignQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{reign.Label}
	default:
		err = &NotSingularError{reign.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *ReignQuery) OnlyIDX(ctx context.Context) int {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Reigns.
func (rq *ReignQuery) All(ctx context.Context) ([]*Reign, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Reign, *ReignQuery]()
	return withInterceptors[[]*Reign](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *ReignQuery) AllX(ctx context.Context) []*Reign {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Reign IDs.
func (rq *ReignQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err := rq.Select(reign.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *ReignQuery) IDsX(ctx context.Context) []int {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *ReignQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*ReignQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *ReignQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *ReignQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *ReignQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReignQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *ReignQuery) Clone() *ReignQuery {
	if rq == nil {
		return nil
	}
	return &ReignQuery{
		config:      rq.config,
		ctx:         rq.ctx.Clone(),
		order:       append([]OrderFunc{}, rq.order...),
		inters:      append([]Interceptor{}, rq.inters...),
		predicates:  append([]predicate.Reign{}, rq.predicates...),
		withBattery: rq.withBattery.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithBattery tells the query-builder to eager-load the nodes that are connected to
// the "battery" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ReignQuery) WithBattery(opts ...func(*BatteryQuery)) *ReignQuery {
	query := (&BatteryClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withBattery = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Action batdef.ReignAction `json:"action,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Reign.Query().
//		GroupBy(reign.FieldAction).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *ReignQuery) GroupBy(field string, fields ...string) *ReignGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReignGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = reign.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Action batdef.ReignAction `json:"action,omitempty"`
//	}
//
//	client.Reign.Query().
//		Select(reign.FieldAction).
//		Scan(ctx, &v)
func (rq *ReignQuery) Select(fields ...string) *ReignSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &ReignSelect{ReignQuery: rq}
	sbuild.label = reign.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReignSelect configured with the given aggregations.
func (rq *ReignQuery) Aggregate(fns ...AggregateFunc) *ReignSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *ReignQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !reign.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *ReignQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Reign, error) {
	var (
		nodes       = []*Reign{}
		_spec       = rq.querySpec()
		loadedTypes = [1]bool{
			rq.withBattery != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Reign).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Reign{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(rq.modifiers) > 0 {
		_spec.Modifiers = rq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withBattery; query != nil {
		if err := rq.loadBattery(ctx, query, nodes, nil,
			func(n *Reign, e *Battery) { n.Edges.Battery = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *ReignQuery) loadBattery(ctx context.Context, query *BatteryQuery, nodes []*Reign, init func(*Reign), assign func(*Reign, *Battery)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Reign)
	for i := range nodes {
		fk := nodes[i].BatteryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(battery.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "battery_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rq *ReignQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	if len(rq.modifiers) > 0 {
		_spec.Modifiers = rq.modifiers
	}
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *ReignQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   reign.Table,
			Columns: reign.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: reign.FieldID,
			},
		},
		From:   rq.sql,
		Unique: true,
	}
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reign.FieldID)
		for i := range fields {
			if fields[i] != reign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *ReignQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(reign.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = reign.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range rq.modifiers {
		m(selector)
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rq *ReignQuery) Modify(modifiers ...func(s *sql.Selector)) *ReignSelect {
	rq.modifiers = append(rq.modifiers, modifiers...)
	return rq.Select()
}

// ReignGroupBy is the group-by builder for Reign entities.
type ReignGroupBy struct {
	selector
	build *ReignQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *ReignGroupBy) Aggregate(fns ...AggregateFunc) *ReignGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *ReignGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReignQuery, *ReignGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *ReignGroupBy) sqlScan(ctx context.Context, root *ReignQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReignSelect is the builder for selecting fields of Reign entities.
type ReignSelect struct {
	*ReignQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *ReignSelect) Aggregate(fns ...AggregateFunc) *ReignSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *ReignSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReignQuery, *ReignSelect](ctx, rs.ReignQuery, rs, rs.inters, v)
}

func (rs *ReignSelect) sqlScan(ctx context.Context, root *ReignQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (rs *ReignSelect) Modify(modifiers ...func(s *sql.Selector)) *ReignSelect {
	rs.modifiers = append(rs.modifiers, modifiers...)
	return rs
}
