// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: battery.proto

package proto

import (
	entpb "github.com/auroraride/adapter/defs/xcdef/proto/entpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatteryQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BatteryQueryRequest) Reset() {
	*x = BatteryQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatteryQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryQueryRequest) ProtoMessage() {}

func (x *BatteryQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryQueryRequest.ProtoReflect.Descriptor instead.
func (*BatteryQueryRequest) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{0}
}

func (x *BatteryQueryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BatteryBatchQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *BatteryBatchQueryRequest) Reset() {
	*x = BatteryBatchQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatteryBatchQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryBatchQueryRequest) ProtoMessage() {}

func (x *BatteryBatchQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryBatchQueryRequest.ProtoReflect.Descriptor instead.
func (*BatteryBatchQueryRequest) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{1}
}

func (x *BatteryBatchQueryRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatterySampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*BatterySampleResponse_Battery `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BatterySampleResponse) Reset() {
	*x = BatterySampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatterySampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatterySampleResponse) ProtoMessage() {}

func (x *BatterySampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatterySampleResponse.ProtoReflect.Descriptor instead.
func (*BatterySampleResponse) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{2}
}

func (x *BatterySampleResponse) GetItems() []*BatterySampleResponse_Battery {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatterySampleResponse_Battery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sn        string  `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Soc       *uint32 `protobuf:"varint,3,opt,name=soc,proto3,oneof" json:"soc,omitempty"`                             // 剩余电量百分比
	MosStatus []byte  `protobuf:"bytes,4,opt,name=mos_status,json=mosStatus,proto3,oneof" json:"mos_status,omitempty"` // mos状态
	Faults    []byte  `protobuf:"bytes,5,opt,name=faults,proto3,oneof" json:"faults,omitempty"`                        // 故障列表
	InCabinet *bool   `protobuf:"varint,6,opt,name=in_cabinet,json=inCabinet,proto3,oneof" json:"in_cabinet,omitempty"`
}

func (x *BatterySampleResponse_Battery) Reset() {
	*x = BatterySampleResponse_Battery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatterySampleResponse_Battery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatterySampleResponse_Battery) ProtoMessage() {}

func (x *BatterySampleResponse_Battery) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatterySampleResponse_Battery.ProtoReflect.Descriptor instead.
func (*BatterySampleResponse_Battery) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BatterySampleResponse_Battery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BatterySampleResponse_Battery) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *BatterySampleResponse_Battery) GetSoc() uint32 {
	if x != nil && x.Soc != nil {
		return *x.Soc
	}
	return 0
}

func (x *BatterySampleResponse_Battery) GetMosStatus() []byte {
	if x != nil {
		return x.MosStatus
	}
	return nil
}

func (x *BatterySampleResponse_Battery) GetFaults() []byte {
	if x != nil {
		return x.Faults
	}
	return nil
}

func (x *BatterySampleResponse_Battery) GetInCabinet() bool {
	if x != nil && x.InCabinet != nil {
		return *x.InCabinet
	}
	return false
}

var File_battery_proto protoreflect.FileDescriptor

var file_battery_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x6e,
	0x74, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x13, 0x42, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2c, 0x0a, 0x18, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xac,
	0x02, 0x0a, 0x15, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x1a, 0xd6, 0x01, 0x0a, 0x07, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x6e,
	0x12, 0x15, 0x0a, 0x03, 0x73, 0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52,
	0x03, 0x73, 0x6f, 0x63, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x6d, 0x6f, 0x73, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x09, 0x6d,
	0x6f, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x02, 0x52, 0x06, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x73, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x69, 0x6e, 0x5f, 0x63,
	0x61, 0x62, 0x69, 0x6e, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52, 0x09,
	0x69, 0x6e, 0x43, 0x61, 0x62, 0x69, 0x6e, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x73, 0x6f, 0x63, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6d, 0x6f, 0x73, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x62, 0x69, 0x6e, 0x65, 0x74, 0x32, 0xa3, 0x01,
	0x0a, 0x0e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0e, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x12, 0x51, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x75, 0x72, 0x6f, 0x72, 0x61, 0x72, 0x69, 0x64, 0x65, 0x2f, 0x61, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x2f, 0x64, 0x65, 0x66, 0x73, 0x2f, 0x78, 0x63, 0x64, 0x65, 0x66, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_battery_proto_rawDescOnce sync.Once
	file_battery_proto_rawDescData = file_battery_proto_rawDesc
)

func file_battery_proto_rawDescGZIP() []byte {
	file_battery_proto_rawDescOnce.Do(func() {
		file_battery_proto_rawDescData = protoimpl.X.CompressGZIP(file_battery_proto_rawDescData)
	})
	return file_battery_proto_rawDescData
}

var file_battery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_battery_proto_goTypes = []interface{}{
	(*BatteryQueryRequest)(nil),           // 0: proto.BatteryQueryRequest
	(*BatteryBatchQueryRequest)(nil),      // 1: proto.BatteryBatchQueryRequest
	(*BatterySampleResponse)(nil),         // 2: proto.BatterySampleResponse
	(*BatterySampleResponse_Battery)(nil), // 3: proto.BatterySampleResponse.Battery
	(*entpb.Battery)(nil),                 // 4: entpb.Battery
}
var file_battery_proto_depIdxs = []int32{
	3, // 0: proto.BatterySampleResponse.items:type_name -> proto.BatterySampleResponse.Battery
	0, // 1: proto.BatteryService.GetBatteryDetail:input_type -> proto.BatteryQueryRequest
	1, // 2: proto.BatteryService.GetBatterySample:input_type -> proto.BatteryBatchQueryRequest
	4, // 3: proto.BatteryService.GetBatteryDetail:output_type -> entpb.Battery
	2, // 4: proto.BatteryService.GetBatterySample:output_type -> proto.BatterySampleResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_battery_proto_init() }
func file_battery_proto_init() {
	if File_battery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_battery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatteryQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatteryBatchQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatterySampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatterySampleResponse_Battery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_battery_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_battery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_battery_proto_goTypes,
		DependencyIndexes: file_battery_proto_depIdxs,
		MessageInfos:      file_battery_proto_msgTypes,
	}.Build()
	File_battery_proto = out.File
	file_battery_proto_rawDesc = nil
	file_battery_proto_goTypes = nil
	file_battery_proto_depIdxs = nil
}
