// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: battery.proto

package proto

import (
	entpb "github.com/auroraride/adapter/defs/xcdef/proto/entpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatteryQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn string `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
}

func (x *BatteryQueryRequest) Reset() {
	*x = BatteryQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatteryQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryQueryRequest) ProtoMessage() {}

func (x *BatteryQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryQueryRequest.ProtoReflect.Descriptor instead.
func (*BatteryQueryRequest) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{0}
}

func (x *BatteryQueryRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type BatteryBatchQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn []string `protobuf:"bytes,1,rep,name=sn,proto3" json:"sn,omitempty"`
}

func (x *BatteryBatchQueryRequest) Reset() {
	*x = BatteryBatchQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatteryBatchQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryBatchQueryRequest) ProtoMessage() {}

func (x *BatteryBatchQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryBatchQueryRequest.ProtoReflect.Descriptor instead.
func (*BatteryBatchQueryRequest) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{1}
}

func (x *BatteryBatchQueryRequest) GetSn() []string {
	if x != nil {
		return x.Sn
	}
	return nil
}

type BatterySampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*entpb.Heartbeat `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BatterySampleResponse) Reset() {
	*x = BatterySampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatterySampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatterySampleResponse) ProtoMessage() {}

func (x *BatterySampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatterySampleResponse.ProtoReflect.Descriptor instead.
func (*BatterySampleResponse) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{2}
}

func (x *BatterySampleResponse) GetItems() []*entpb.Heartbeat {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_battery_proto protoreflect.FileDescriptor

var file_battery_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x6e,
	0x74, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x13, 0x42, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x6e,
	0x22, 0x2a, 0x0a, 0x18, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x73, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x73, 0x6e, 0x22, 0x3f, 0x0a, 0x15,
	0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x9c, 0x01,
	0x0a, 0x07, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x65, 0x6e, 0x74, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x51, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x72, 0x6f, 0x72,
	0x61, 0x72, 0x69, 0x64, 0x65, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x64, 0x65,
	0x66, 0x73, 0x2f, 0x78, 0x63, 0x64, 0x65, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_battery_proto_rawDescOnce sync.Once
	file_battery_proto_rawDescData = file_battery_proto_rawDesc
)

func file_battery_proto_rawDescGZIP() []byte {
	file_battery_proto_rawDescOnce.Do(func() {
		file_battery_proto_rawDescData = protoimpl.X.CompressGZIP(file_battery_proto_rawDescData)
	})
	return file_battery_proto_rawDescData
}

var file_battery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_battery_proto_goTypes = []interface{}{
	(*BatteryQueryRequest)(nil),      // 0: proto.BatteryQueryRequest
	(*BatteryBatchQueryRequest)(nil), // 1: proto.BatteryBatchQueryRequest
	(*BatterySampleResponse)(nil),    // 2: proto.BatterySampleResponse
	(*entpb.Heartbeat)(nil),          // 3: entpb.Heartbeat
	(*entpb.Battery)(nil),            // 4: entpb.Battery
}
var file_battery_proto_depIdxs = []int32{
	3, // 0: proto.BatterySampleResponse.items:type_name -> entpb.Heartbeat
	0, // 1: proto.Battery.GetBatteryDetail:input_type -> proto.BatteryQueryRequest
	1, // 2: proto.Battery.GetBatterySample:input_type -> proto.BatteryBatchQueryRequest
	4, // 3: proto.Battery.GetBatteryDetail:output_type -> entpb.Battery
	2, // 4: proto.Battery.GetBatterySample:output_type -> proto.BatterySampleResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_battery_proto_init() }
func file_battery_proto_init() {
	if File_battery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_battery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatteryQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatteryBatchQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatterySampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_battery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_battery_proto_goTypes,
		DependencyIndexes: file_battery_proto_depIdxs,
		MessageInfos:      file_battery_proto_msgTypes,
	}.Build()
	File_battery_proto = out.File
	file_battery_proto_rawDesc = nil
	file_battery_proto_goTypes = nil
	file_battery_proto_depIdxs = nil
}
