// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Battery is the predicate function for battery builders.
type Battery func(*sql.Selector)

// Fault is the predicate function for fault builders.
type Fault func(*sql.Selector)

// Heartbeat is the predicate function for heartbeat builders.
type Heartbeat func(*sql.Selector)

// Reign is the predicate function for reign builders.
type Reign func(*sql.Selector)
