// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: battery.proto

package pb

import (
	xcpb "github.com/auroraride/adapter/rpc/pb/xcpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatterySnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn string `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
}

func (x *BatterySnRequest) Reset() {
	*x = BatterySnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatterySnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatterySnRequest) ProtoMessage() {}

func (x *BatterySnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatterySnRequest.ProtoReflect.Descriptor instead.
func (*BatterySnRequest) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{0}
}

func (x *BatterySnRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type BatteryBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn []string `protobuf:"bytes,1,rep,name=sn,proto3" json:"sn,omitempty"`
}

func (x *BatteryBatchRequest) Reset() {
	*x = BatteryBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatteryBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryBatchRequest) ProtoMessage() {}

func (x *BatteryBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryBatchRequest.ProtoReflect.Descriptor instead.
func (*BatteryBatchRequest) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{1}
}

func (x *BatteryBatchRequest) GetSn() []string {
	if x != nil {
		return x.Sn
	}
	return nil
}

type BatteryBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string]*xcpb.Battery `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BatteryBatchResponse) Reset() {
	*x = BatteryBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatteryBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryBatchResponse) ProtoMessage() {}

func (x *BatteryBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryBatchResponse.ProtoReflect.Descriptor instead.
func (*BatteryBatchResponse) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{2}
}

func (x *BatteryBatchResponse) GetItems() map[string]*xcpb.Battery {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatterySampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voltage float64 `protobuf:"fixed64,1,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current float64 `protobuf:"fixed64,2,opt,name=current,proto3" json:"current,omitempty"`
	Soc     uint32  `protobuf:"varint,3,opt,name=soc,proto3" json:"soc,omitempty"`
	Geom    []byte  `protobuf:"bytes,4,opt,name=geom,proto3" json:"geom,omitempty"`
}

func (x *BatterySampleResponse) Reset() {
	*x = BatterySampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_battery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatterySampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatterySampleResponse) ProtoMessage() {}

func (x *BatterySampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatterySampleResponse.ProtoReflect.Descriptor instead.
func (*BatterySampleResponse) Descriptor() ([]byte, []int) {
	return file_battery_proto_rawDescGZIP(), []int{3}
}

func (x *BatterySampleResponse) GetVoltage() float64 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *BatterySampleResponse) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *BatterySampleResponse) GetSoc() uint32 {
	if x != nil {
		return x.Soc
	}
	return 0
}

func (x *BatterySampleResponse) GetGeom() []byte {
	if x != nil {
		return x.Geom
	}
	return nil
}

var File_battery_proto protoreflect.FileDescriptor

var file_battery_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x0f, 0x78, 0x63, 0x70, 0x62, 0x2f, 0x78, 0x63, 0x70, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x6e, 0x22, 0x25, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x73, 0x6e, 0x22,
	0x9a, 0x01, 0x0a, 0x14, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x1a, 0x47, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x78, 0x63, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x71, 0x0a, 0x15,
	0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6f, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x65, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x67, 0x65, 0x6f, 0x6d, 0x32,
	0x80, 0x01, 0x0a, 0x07, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x3a, 0x0a, 0x05, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x53, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x53, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x75, 0x72, 0x6f, 0x72, 0x61, 0x72, 0x69, 0x64, 0x65, 0x2f, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_battery_proto_rawDescOnce sync.Once
	file_battery_proto_rawDescData = file_battery_proto_rawDesc
)

func file_battery_proto_rawDescGZIP() []byte {
	file_battery_proto_rawDescOnce.Do(func() {
		file_battery_proto_rawDescData = protoimpl.X.CompressGZIP(file_battery_proto_rawDescData)
	})
	return file_battery_proto_rawDescData
}

var file_battery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_battery_proto_goTypes = []interface{}{
	(*BatterySnRequest)(nil),      // 0: pb.BatterySnRequest
	(*BatteryBatchRequest)(nil),   // 1: pb.BatteryBatchRequest
	(*BatteryBatchResponse)(nil),  // 2: pb.BatteryBatchResponse
	(*BatterySampleResponse)(nil), // 3: pb.BatterySampleResponse
	nil,                           // 4: pb.BatteryBatchResponse.ItemsEntry
	(*xcpb.Battery)(nil),          // 5: xcpb.Battery
}
var file_battery_proto_depIdxs = []int32{
	4, // 0: pb.BatteryBatchResponse.items:type_name -> pb.BatteryBatchResponse.ItemsEntry
	5, // 1: pb.BatteryBatchResponse.ItemsEntry.value:type_name -> xcpb.Battery
	1, // 2: pb.Battery.Batch:input_type -> pb.BatteryBatchRequest
	0, // 3: pb.Battery.Sample:input_type -> pb.BatterySnRequest
	2, // 4: pb.Battery.Batch:output_type -> pb.BatteryBatchResponse
	3, // 5: pb.Battery.Sample:output_type -> pb.BatterySampleResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_battery_proto_init() }
func file_battery_proto_init() {
	if File_battery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_battery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatterySnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatteryBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatteryBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_battery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatterySampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_battery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_battery_proto_goTypes,
		DependencyIndexes: file_battery_proto_depIdxs,
		MessageInfos:      file_battery_proto_msgTypes,
	}.Build()
	File_battery_proto = out.File
	file_battery_proto_rawDesc = nil
	file_battery_proto_goTypes = nil
	file_battery_proto_depIdxs = nil
}
